<?php

use Illuminate\Database\Seeder;

class EmployeesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $employees = [
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'NELVIS', 'second_name' => 'IRENE', 'last_name' => 'ALARCON', 'mothers_last_name' => 'PIZARROSO', 'identity_card' => '8326080', 'birth_date' => date("Y-m-d", strtotime('06/28/1991')) , 'account_number'  => '10000009743738', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'JOHNNY', 'second_name' => 'JUNIOR', 'last_name' => 'ALAVE', 'mothers_last_name' => 'GUTIERREZ', 'identity_card' => '6096967', 'birth_date' => date("Y-m-d", strtotime('12/18/1984')) , 'account_number'  => '10000018696358', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'FERNANDA', 'second_name' => '', 'last_name' => 'ALEGRIA', 'mothers_last_name' => 'ACARAPI', 'identity_card' => '2449068', 'birth_date' => date("Y-m-d", strtotime('07/07/1962')) , 'account_number'  => '10000012934655', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'CONSUELO_DEL_CARMEN', 'second_name' => '', 'last_name' => 'ALIAGA', 'mothers_last_name' => 'RIVERO', 'identity_card' => '4268839', 'birth_date' => date("Y-m-d", strtotime('02/19/1974')) , 'account_number'  => '10000021210054', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'DAYNOR', 'second_name' => '', 'last_name' => 'APO', 'mothers_last_name' => 'SILLO', 'identity_card' => '6866195', 'birth_date' => date("Y-m-d", strtotime('10/14/1990')) , 'account_number'  => '10000026456760', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'MARIA', 'second_name' => 'ANTONIETA_MIRNA', 'last_name' => 'ALVAREZ', 'mothers_last_name' => 'CASTILLO', 'identity_card' => '6848816', 'birth_date' => date("Y-m-d", strtotime('08/09/1990')) , 'account_number'  => '10000017766631', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'NANCY', 'second_name' => '', 'last_name' => 'AVILES', 'mothers_last_name' => 'MAMANI', 'identity_card' => '3478970', 'birth_date' => date("Y-m-d", strtotime('03/16/1982')) , 'account_number'  => '10000024330685', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 3, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'FELIX', 'second_name' => '', 'last_name' => 'BALDERRAMA', 'mothers_last_name' => 'VEIZAGA', 'identity_card' => '5907833', 'birth_date' => date("Y-m-d", strtotime('02/03/1983')) , 'account_number'  => '10000003702657', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'BRYAN', 'second_name' => 'FREDDY', 'last_name' => 'BRAÑEZ', 'mothers_last_name' => 'TAPIA', 'identity_card' => '4756336', 'birth_date' => date("Y-m-d", strtotime('06/06/1981')) , 'account_number'  => '10000017702974', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'IVAN', 'second_name' => 'MARIO', 'last_name' => 'BOLIVAR', 'mothers_last_name' => 'PARRAGA', 'identity_card' => '2286661', 'birth_date' => date("Y-m-d", strtotime('01/19/1965')) , 'account_number'  => '10000026997011', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'GABRIELA', 'second_name' => 'JACKELINE', 'last_name' => 'BUSTILLOS', 'mothers_last_name' => 'LANDAETA', 'identity_card' => '4285006', 'birth_date' => date("Y-m-d", strtotime('03/18/1978')) , 'account_number'  => '10000012911827', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'JUAN', 'second_name' => 'JOSE', 'last_name' => 'CALLE', 'mothers_last_name' => 'CABRERA', 'identity_card' => '8358651', 'birth_date' => date("Y-m-d", strtotime('05/06/1993')) , 'account_number'  => '10000021455428', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'GABRIELA', 'second_name' => 'CAROLINA', 'last_name' => 'CANAZA', 'mothers_last_name' => 'CHOQUE', 'identity_card' => '6117948', 'birth_date' => date("Y-m-d", strtotime('12/11/1987')) , 'account_number'  => '10000023054517', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'MARIA', 'second_name' => 'LUZ', 'last_name' => 'COAQUIRA', 'mothers_last_name' => 'TICONA', 'identity_card' => '4265887', 'birth_date' => date("Y-m-d", strtotime('04/09/1974')) , 'account_number'  => '10000017220033', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 6, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'JHESSY', 'second_name' => 'JHEOVANA', 'last_name' => 'COCA', 'mothers_last_name' => 'CABRERA', 'identity_card' => '6629776', 'birth_date' => date("Y-m-d", strtotime('10/31/1985')) , 'account_number'  => '10000009299533', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'ROSARIO', 'second_name' => 'LUISA', 'last_name' => 'CORI', 'mothers_last_name' => 'MANCILLA', 'identity_card' => '5948875', 'birth_date' => date("Y-m-d", strtotime('06/21/1981')) , 'account_number'  => '10000018381503', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'JHONNY', 'second_name' => 'DONATO', 'last_name' => 'CORONEL', 'mothers_last_name' => 'AYALA', 'identity_card' => '2616779', 'birth_date' => date("Y-m-d", strtotime('02/04/1964')) , 'account_number'  => '10000004763814', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'XIMENA', 'second_name' => '', 'last_name' => 'CRUZ', 'mothers_last_name' => 'LAUREL', 'identity_card' => '9202221', 'birth_date' => date("Y-m-d", strtotime('07/08/1979')) , 'account_number'  => '10000017547669', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'CAROLINA', 'second_name' => 'ISABEL', 'last_name' => 'CRUZ', 'mothers_last_name' => 'MANCILLA', 'identity_card' => '4836141', 'birth_date' => date("Y-m-d", strtotime('09/08/1978')) , 'account_number'  => '10000018607636', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'RAUL', 'second_name' => 'EDUARDO', 'last_name' => 'DURAN', 'mothers_last_name' => 'CHOQUE', 'identity_card' => '3359403', 'birth_date' => date("Y-m-d", strtotime('10/13/1971')) , 'account_number'  => '10000010647630', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'PATRICIA', 'second_name' => 'DORA', 'last_name' => 'FERNANDEZ', 'mothers_last_name' => 'CORTEZ', 'identity_card' => '4279388', 'birth_date' => date("Y-m-d", strtotime('04/14/1974')) , 'account_number'  => '10000017526605', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'JUAN', 'second_name' => 'MARCOS', 'last_name' => 'GERL', 'mothers_last_name' => 'PARDO', 'identity_card' => '2379075', 'birth_date' => date("Y-m-d", strtotime('08/29/1960')) , 'account_number'  => '10000004184630', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'JUAN', 'second_name' => 'CARLOS', 'last_name' => 'GONZALES', 'mothers_last_name' => 'CAHUAYA', 'identity_card' => '4322190', 'birth_date' => date("Y-m-d", strtotime('02/22/1978')) , 'account_number'  => '10000027153464', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'JAVIER', 'second_name' => 'SAMUEL', 'last_name' => 'GUERRERO', 'mothers_last_name' => 'JORDAN', 'identity_card' => '3342271', 'birth_date' => date("Y-m-d", strtotime('08/02/1972')) , 'account_number'  => '10000006021749', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'ALEJANDRO', 'second_name' => 'ERICK', 'last_name' => 'GUISBERT', 'mothers_last_name' => 'FLOR', 'identity_card' => '4771553', 'birth_date' => date("Y-m-d", strtotime('12/18/1988')) , 'account_number'  => '10000020805830', 'gender' => 'M'],            
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'MARCELO', 'second_name' => '', 'last_name' => 'GUTIERREZ', 'mothers_last_name' => 'BUTRON', 'identity_card' => '3358454', 'birth_date' => date("Y-m-d", strtotime('10/04/2017')) , 'account_number'  => '10000025296125', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'AIDE', 'second_name' => 'LEONOR', 'last_name' => 'GUTIERREZ', 'mothers_last_name' => 'QUISBERT', 'identity_card' => '5990351', 'birth_date' => date("Y-m-d", strtotime('11/27/1979')) , 'account_number'  => '10000021574096', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'JUSTINO', 'second_name' => '', 'last_name' => 'HUAMPO', 'mothers_last_name' => 'CALLISAYA', 'identity_card' => '6800779', 'birth_date' => date("Y-m-d", strtotime('06/01/1978')) , 'account_number'  => '10000020165234', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'MAURICIO', 'second_name' => 'FELIX', 'last_name' => 'IRIARTE', 'mothers_last_name' => 'VALENZUELA', 'identity_card' => '4875775', 'birth_date' => date("Y-m-d", strtotime('08/08/1988')) , 'account_number'  => '10000026705787', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'ANA', 'second_name' => 'GABRIELA', 'last_name' => 'JAUREGUI', 'mothers_last_name' => 'AGUILAR', 'identity_card' => '8277418', 'birth_date' => date("Y-m-d", strtotime('10/10/1993')) , 'account_number'  => '10000024955649', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'RENE', 'second_name' => 'ENRIQUE', 'last_name' => 'JIMENEZ', 'mothers_last_name' => 'ORTEGA', 'identity_card' => '6835843', 'birth_date' => date("Y-m-d", strtotime('01/20/1988')) , 'account_number'  => '10000009346186', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'FRANZ', 'second_name' => '', 'last_name' => 'LAZO', 'mothers_last_name' => 'CHAVEZ', 'identity_card' => '3367169', 'birth_date' => date("Y-m-d", strtotime('11/12/1975')) , 'account_number'  => '10000014710102', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'NELFA', 'second_name' => 'BRIGITTE', 'last_name' => 'LAZARTE', 'mothers_last_name' => 'SALINAS', 'identity_card' => '4294797', 'birth_date' => date("Y-m-d", strtotime('01/08/1974')) , 'account_number'  => '10000004858821', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'ROCIO_DEL_ALBA', 'second_name' => '', 'last_name' => 'JUAREZ', 'mothers_last_name' => 'BERRIOS', 'identity_card' => '4338808', 'birth_date' => date("Y-m-d", strtotime('09/20/1976')) , 'account_number'  => '10000017181326', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'PAMELA', 'second_name' => 'LORENA', 'last_name' => 'LOPEZ', 'mothers_last_name' => 'TORREZ', 'identity_card' => '4887592', 'birth_date' => date("Y-m-d", strtotime('04/20/1981')) , 'account_number'  => '10000009721734', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'VANESSA', 'second_name' => 'LOURDES', 'last_name' => 'LUNA', 'mothers_last_name' => 'CANAVIRI', 'identity_card' => '9115203', 'birth_date' => date("Y-m-d", strtotime('12/16/1992')) , 'account_number'  => '10000025978567', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'JORGE', 'second_name' => 'FRANCISCO', 'last_name' => 'MACHACA', 'mothers_last_name' => 'CALCINA', 'identity_card' => '4881022', 'birth_date' => date("Y-m-d", strtotime('11/23/1980')) , 'account_number'  => '10000024711299', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'ROLANDO', 'second_name' => 'JESUS', 'last_name' => 'MAGNE', 'mothers_last_name' => 'SINGURI', 'identity_card' => '4748496', 'birth_date' => date("Y-m-d", strtotime('11/10/1975')) , 'account_number'  => '10000013247049', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'SUSANA', 'second_name' => 'EUSEBIA', 'last_name' => 'MAMANI', 'mothers_last_name' => 'QUISPE', 'identity_card' => '4904484', 'birth_date' => date("Y-m-d", strtotime('10/29/1983')) , 'account_number'  => '10000025202221', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 6, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'FEDRA', 'second_name' => 'ARLEEN', 'last_name' => 'MARTINEZ', 'mothers_last_name' => 'ARANCIBIA', 'identity_card' => '6684488', 'birth_date' => date("Y-m-d", strtotime('10/05/1988')) , 'account_number'  => '10000019437305', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'MARIA_DEL_CARMEN', 'second_name' => 'CECILIA', 'last_name' => 'MAZZI', 'mothers_last_name' => 'SILVA', 'identity_card' => '487687', 'birth_date' => date("Y-m-d", strtotime('04/27/1967')) , 'account_number'  => '10000006342632', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'GUILLERMO', 'second_name' => '', 'last_name' => 'MEJILLONES', 'mothers_last_name' => 'QUISPE', 'identity_card' => '6161763', 'birth_date' => date("Y-m-d", strtotime('06/08/1983')) , 'account_number'  => '10000006006361', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'TATIANA', 'second_name' => 'GABRIELA', 'last_name' => 'MENA', 'mothers_last_name' => 'AMARU', 'identity_card' => '6722699', 'birth_date' => date("Y-m-d", strtotime('03/18/1987')) , 'account_number'  => '10000026313358', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'VERONICA', 'second_name' => 'FELICIDAD', 'last_name' => 'MERCADO', 'mothers_last_name' => 'FLORES', 'identity_card' => '6052573', 'birth_date' => date("Y-m-d", strtotime('03/19/1985')) , 'account_number'  => '10000017229291', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'HILDA', 'second_name' => 'THANIA', 'last_name' => 'MORALES', 'mothers_last_name' => 'PINAYA', 'identity_card' => '4837063', 'birth_date' => date("Y-m-d", strtotime('12/29/1980')) , 'account_number'  => '10000016745503', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'JESUS', 'second_name' => '', 'last_name' => 'MORALES', 'mothers_last_name' => 'MORENO', 'identity_card' => '1061549-1U', 'birth_date' => date("Y-m-d", strtotime('07/31/1959')) , 'account_number'  => '10000005007104', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 2, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'KAREN', 'second_name' => 'ANDREA', 'last_name' => 'MURILLO', 'mothers_last_name' => 'ROMERO', 'identity_card' => '5695109', 'birth_date' => date("Y-m-d", strtotime('03/24/1988')) , 'account_number'  => '10000022964650', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'ANA', 'second_name' => 'MARIA', 'last_name' => 'NUÑEZ', 'mothers_last_name' => 'SEJAS', 'identity_card' => '3350777', 'birth_date' => date("Y-m-d", strtotime('02/19/1969')) , 'account_number'  => '10000017230876', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'RAUL', 'second_name' => '', 'last_name' => 'OVANDO', 'mothers_last_name' => 'NIETO', 'identity_card' => '2068484', 'birth_date' => date("Y-m-d", strtotime('09/17/1959')) , 'account_number'  => '10000010580591', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'WILMER', 'second_name' => 'EMIGDIO', 'last_name' => 'PAUCARA', 'mothers_last_name' => 'RAMOS', 'identity_card' => '4326798', 'birth_date' => date("Y-m-d", strtotime('11/13/1981')) , 'account_number'  => '10000017229530', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'ALFREDO', 'second_name' => 'AGUSTIN', 'last_name' => 'PEREZ', 'mothers_last_name' => 'ALANOCA', 'identity_card' => '2430451', 'birth_date' => date("Y-m-d", strtotime('08/05/1963')) , 'account_number'  => '10000024197564', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'CINTHYA', 'second_name' => 'GABRIELA', 'last_name' => 'QUISBERT', 'mothers_last_name' => 'POMA', 'identity_card' => '4886229', 'birth_date' => date("Y-m-d", strtotime('03/15/1983')) , 'account_number'  => '10000019404453', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'MARIA', 'second_name' => 'ELENA', 'last_name' => 'QUISPE', 'mothers_last_name' => 'ALANOCA', 'identity_card' => '5954573', 'birth_date' => date("Y-m-d", strtotime('01/20/1980')) , 'account_number'  => '10000017220083', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'GONZALO', 'second_name' => '', 'last_name' => 'QUISPE', 'mothers_last_name' => 'FLORES', 'identity_card' => '6076133', 'birth_date' => date("Y-m-d", strtotime('01/02/1988')) , 'account_number'  => '10000018294954', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'AMALIA', 'second_name' => '', 'last_name' => 'QUISPE', 'mothers_last_name' => 'SIRPA', 'identity_card' => '4907550', 'birth_date' => date("Y-m-d", strtotime('07/10/1981')) , 'account_number'  => '10000024254653', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'MARIELA', 'second_name' => 'MARIA', 'last_name' => 'RAMOS', 'mothers_last_name' => 'CORANI', 'identity_card' => '6987176', 'birth_date' => date("Y-m-d", strtotime('02/21/1988')) , 'account_number'  => '10000022278019', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'VANESSA', 'second_name' => 'JACQUELINE', 'last_name' => 'ROCA', 'mothers_last_name' => 'TROCHE', 'identity_card' => '10931325', 'birth_date' => date("Y-m-d", strtotime('09/22/1992')) , 'account_number'  => '10000018664206', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'MARIA', 'second_name' => 'INES', 'last_name' => 'ROMAN', 'mothers_last_name' => 'QUIROGA', 'identity_card' => '5960790', 'birth_date' => date("Y-m-d", strtotime('01/15/1982')) , 'account_number'  => '10000017222914', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'OSCAR', 'second_name' => 'HILARION', 'last_name' => 'ROMERO', 'mothers_last_name' => 'SILVA', 'identity_card' => '4851948', 'birth_date' => date("Y-m-d", strtotime('06/15/1986')) , 'account_number'  => '10000017694113', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'RONALD', 'second_name' => 'LUIS', 'last_name' => 'SANCHEZ', 'mothers_last_name' => 'MOLINA', 'identity_card' => '4919607', 'birth_date' => date("Y-m-d", strtotime('01/04/1980')) , 'account_number'  => '10000020808321', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'ERLAND', 'second_name' => 'GASTON', 'last_name' => 'SARAVIA', 'mothers_last_name' => 'BELTRAN', 'identity_card' => '3454752', 'birth_date' => date("Y-m-d", strtotime('08/07/1974')) , 'account_number'  => '10000012056920', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'CLAUDIA', 'second_name' => 'CRISTAL', 'last_name' => 'TABOADA', 'mothers_last_name' => 'ROCHA', 'identity_card' => '4885095', 'birth_date' => date("Y-m-d", strtotime('02/25/1983')) , 'account_number'  => '', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'FERNANDO', 'second_name' => '', 'last_name' => 'TICONA', 'mothers_last_name' => 'APAZA', 'identity_card' => '4781199', 'birth_date' => date("Y-m-d", strtotime('12/27/1975')) , 'account_number'  => '10000009497418', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'DAGMAR', 'second_name' => 'MILENKA', 'last_name' => 'TOVAR', 'mothers_last_name' => 'EYZAGUIRRE', 'identity_card' => '6833123', 'birth_date' => date("Y-m-d", strtotime('07/25/1988')) , 'account_number'  => '10000025048378', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'TAMY', 'second_name' => '', 'last_name' => 'UGARTE', 'mothers_last_name' => 'MALDONADO', 'identity_card' => '6083462', 'birth_date' => date("Y-m-d", strtotime('11/03/2017')) , 'account_number'  => '10000025884285', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'WALDO', 'second_name' => '', 'last_name' => 'VACA', 'mothers_last_name' => 'ALVAREZ', 'identity_card' => '6102450', 'birth_date' => date("Y-m-d", strtotime('08/30/1985')) , 'account_number'  => '10000026701644', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'VALENTIN', 'second_name' => '', 'last_name' => 'VALDEZ', 'mothers_last_name' => 'MACHACA', 'identity_card' => '2259918', 'birth_date' => date("Y-m-d", strtotime('01/29/1970')) , 'account_number'  => '10000017231147', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'MARIA', 'second_name' => 'R', 'last_name' => 'VARGAS', 'mothers_last_name' => 'LAIME', 'identity_card' => '4905146', 'birth_date' => date("Y-m-d", strtotime('09/29/1981')) , 'account_number'  => '10000004990277', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'ELIZABETH', 'second_name' => 'SABINA', 'last_name' => 'VILLCA', 'mothers_last_name' => 'JUCHANI', 'identity_card' => '4959444', 'birth_date' => date("Y-m-d", strtotime('12/30/1979')) , 'account_number'  => '10000017231816', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'PATRICIA', 'second_name' => 'ELIANA', 'last_name' => 'AGUAYO', 'mothers_last_name' => 'TORREZ', 'identity_card' => '6759405', 'birth_date' => date("Y-m-d", strtotime('01/31/1986')) , 'account_number'  => '10000017231329', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 5, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'MARY', 'second_name' => '', 'last_name' => 'SALAZAR', 'mothers_last_name' => 'GUERRA', 'identity_card' => '5746099', 'birth_date' => date("Y-m-d", strtotime('09/15/1966')) , 'account_number'  => '10000017235545', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 2, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'KAREN', 'second_name' => 'MELISA', 'last_name' => 'MORON', 'mothers_last_name' => 'PORCEL', 'identity_card' => '7555331', 'birth_date' => date("Y-m-d", strtotime('12/06/1989')) , 'account_number'  => '10000017753109', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 3, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'ANA', 'second_name' => 'MARIA', 'last_name' => 'VERDUGUEZ', 'mothers_last_name' => 'CLAROS', 'identity_card' => '5266782', 'birth_date' => date("Y-m-d", strtotime('01/07/1979')) , 'account_number'  => '10000007768738', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 8, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'AMPARITO', 'second_name' => 'ELIZABETH', 'last_name' => 'PARADA', 'mothers_last_name' => 'MENDEZ', 'identity_card' => '2805120', 'birth_date' => date("Y-m-d", strtotime('08/26/1962')) , 'account_number'  => '10000018525771', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 8, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'SILVIA', 'second_name' => 'EUGENIA', 'last_name' => 'TORRICO', 'mothers_last_name' => 'ARNEZ', 'identity_card' => '8943438', 'birth_date' => date("Y-m-d", strtotime('03/03/1991')) , 'account_number'  => '10000017239050', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 2, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'GREGORIO', 'second_name' => '', 'last_name' => 'BALTAZAR', 'mothers_last_name' => 'CONDORI', 'identity_card' => '3653169', 'birth_date' => date("Y-m-d", strtotime('03/14/1980')) , 'account_number'  => '10000018431184', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 6, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'ROSMERY', 'second_name' => '', 'last_name' => 'CAIHUARA', 'mothers_last_name' => 'VELASQUEZ', 'identity_card' => '5500951', 'birth_date' => date("Y-m-d", strtotime('04/01/1980')) , 'account_number'  => '10000018157160', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 9, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'ROSSIO', 'second_name' => '', 'last_name' => 'APARICIO', 'mothers_last_name' => 'ALCOBA', 'identity_card' => '5006621', 'birth_date' => date("Y-m-d", strtotime('09/01/1987')) , 'account_number'  => '10000018170146', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 1, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'MARYSABEL', 'second_name' => '', 'last_name' => 'HURTADO', 'mothers_last_name' => 'CORTEZ', 'identity_card' => '1727172', 'birth_date' => date("Y-m-d", strtotime('07/10/1970')) , 'account_number'  => '10000006182187', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 6, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'LUCIANA', 'second_name' => '', 'last_name' => 'VEGA', 'mothers_last_name' => 'PEREIRA', 'identity_card' => '1765608', 'birth_date' => date("Y-m-d", strtotime('02/07/1981')) , 'account_number'  => '10000021220780', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'MARIA', 'second_name' => 'ISABEL', 'last_name' => 'BARRETO', 'mothers_last_name' => 'GUZMAN', 'identity_card' => '6091225', 'birth_date' => date("Y-m-d", strtotime('04/27/1978')) , 'account_number'  => '10000024635176', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'DAYANA', 'second_name' => '', 'last_name' => 'CHAVEZ', 'mothers_last_name' => 'BITRON', 'identity_card' => '8305603', 'birth_date' => date("Y-m-d", strtotime('10/11/1989')) , 'account_number'  => '10000022144450', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'LUZ', 'second_name' => 'GABRIELA', 'last_name' => 'ESCOBAR', 'mothers_last_name' => 'BUSTAMANTE', 'identity_card' => '6870739', 'birth_date' => date("Y-m-d", strtotime('12/10/1988')) , 'account_number'  => '10000026695912', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'DANY', 'second_name' => 'DANIEL', 'last_name' => 'RAMOS', 'mothers_last_name' => 'QUENTA', 'identity_card' => '6814151', 'birth_date' => date("Y-m-d", strtotime('01/07/1986')) , 'account_number'  => '10000026930459', 'gender' => 'M'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'ADRIANA', 'second_name' => 'KAMIL', 'last_name' => 'HARA', 'mothers_last_name' => 'VELASCO', 'identity_card' => '8310665', 'birth_date' => date("Y-m-d", strtotime('09/09/1989')) , 'account_number'  => '10000026693768', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 2, 'first_name' => 'JUDITH', 'second_name' => '', 'last_name' => 'RAMIREZ', 'mothers_last_name' => 'FLORES', 'identity_card' => '3385877', 'birth_date' => date("Y-m-d", strtotime('09/15/1965')) , 'account_number'  => '10000018201321', 'gender' => 'F'],
            ['employee_type_id' => 2, 'city_identity_card_id' => 4, 'city_birth_id' => 4, 'management_entity_id' => 1, 'first_name' => 'NOELIA', 'second_name' => 'GENESIS', 'last_name' => 'RIOS', 'mothers_last_name' => 'BARRERA', 'identity_card' => '8445876', 'birth_date' => date("Y-m-d", strtotime('02/25/1993')) , 'account_number'  => '10000017087269', 'gender' => 'F']
        ];

        foreach ($employees as $employee) {
            App\Employee::create($employee);
        }
        //factory(App\Employee::class, 200)->create();
    }
}
